[package]
name = "defi-cli"
version = "0.1.0"
edition = "2018"
authors = [
    "DeFi Blockchain Developers <engineering@defichain.com>"
]
description = "DeFichain CLI"

[dependencies]
structopt = "0.3"
defi-rpc = { path = '../rpc-client' }
anyhow = "1.0.44"