[package]
name = "auction-bot"
version = "0.1.0"
edition = "2018"

[dependencies]
defi-rpc = { path = '../rpc-client' }
chain-params = { path = '../chain-params' }
serde_json = "1"
anyhow = "1.0.44"
structopt = "0.3"