name: ParallelTesting
on:
  push:
    branches:
      - parallel-test
  pull_request:
    branches:
      - parallel-test
jobs:
  build-binaries:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Node
      run: ./make.sh build
  sync-matrix:
    strategy:
      matrix:
       datadir:
         - start: 450000
           stop: 500000
         - start: 500000
           stop: 550000
         - start: 550000
           stop: 600000
         - start: 600000
           stop: 650000
         - start: 650000
           stop: 700000
         - start: 700000
           stop: 750000
         - start: 750000
           stop: 800000
    runs-on: [self-hosted, linux, x64]
    needs: build-binaries
    container:
      image : gcr.io/br-blockchains-dev/datadir-${{matrix.datadir.start}}
      volumes:
        - ${{ github.workspace }}/src:/src
        - ${{ github.workspace }}/ci/parallel_sync:/parallel_sync
      options: --privileged
      env:
        STOP_BLOCK: ${{matrix.datadir.stop}}
        DEFID_BIN: /src/defid
        DEFI_CLI_BIN: /src/defi-cli
    timeout-minutes: 4320
    steps:
    - name: Sync and Diff
      run: /parallel_sync/sync_then_diff.
    - name: Show Debug Log
      run: cat $DATADIR/debug.log