name: ParallelTesting
on:
  push:
    branches:
      - parallel-test
  pull_request:
    branches:
      - parallel-test
jobs:
  build-binaries:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Node
      run: ./make.sh build
    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: defibins
        path: |
         src/defid
         src/defi-cli
    - name: Archive Binaries
      uses: actions/upload-artifact@v3
      with:
        name: defibins
        path: |
          src/defid
          src/defi-cli
    - name: Archive Shell Commands
      uses: actions/upload-artifact@v3
      with:
        name: sync
        path: |
          ci/parallel_sync/sync_then_diff.sh

  sync:
    strategy:
      matrix:
        datadir:
          - start: 450000
            stop: 500000
          - start: 500000
            stop: 550000
          - start: 550000
            stop: 600000
          - start: 600000
            stop: 650000
          - start: 650000
            stop: 700000
          - start: 700000
            stop: 750000
          - start: 750000
            stop: 800000
    runs-on: [self-hosted, linux, x64]
    needs: build-binaries
    continue-on-error: true
    container:
      image : gcr.io/br-blockchains-dev/datadir-${{matrix.datadir.start}}
      options: --privileged
      env:
        STOP_BLOCK: ${{matrix.datadir.stop}}
        DEFID_BIN: defid
        DEFI_CLI_BIN: defi-cli
    timeout-minutes: 4320
    steps:
    - name: Download Binaries
      uses: actions/download-artifact@v3
      with:
        name: defibins
    - name: Download Shell Commands
      uses: actions/download-artifact@v3
      with:
        name: sync
    - run: ls -lha ${{ github.workspace }}
    - run: |
        chmod 777 defid
        chmod 777 defi-cli
        chmod 777 sync_then_diff.sh
    - name: Sync and Diff
      run: sync_then_diff.sh
    - name: Show Debug Log
      run: cat $DATADIR/debug.log
