name: ParallelTesting
on:
  push:
    branches:
      - parallel-test
  pull_request:
    branches:
      - parallel-test
jobs:
  build-binaries:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Node
      run: ./make.sh build
#     - name: Upload Defid
#       with:
#         name: defid
#         path: ./src/defid
#     - name: Upload Defi Cli
#       uses: actions/upload-artifact@v3
#       with:
#         name: deficli
#         path: ./src/defi-cli
  # Sync 500000 - 550000
  sync-500000-550000:
    runs-on: [self-hosted, linux, x64]
    needs: build-binaries
    container:
      image : gcr.io/br-blockchains-dev/datadir-500000
      volumes:
        - datadir-500000
        - ${{ github.workspace }}/src:/src
      env:
        STOP_BLOCK: 550000
    timeout-minutes: 4320
    steps:
    - name: Echo user
      run: whoami
    - run: sudo apt install -y wget
#     - uses: actions/checkout@v2
#     - name: Download Defid
#       uses: actions/download-artifact@v3
#       with:
#         name: defid
#     - name: Download Defi Cli
#       uses: actions/download-artifact@v3
#       with:
#         name: defi-cli
    - run: ls -lh /src
    - name: download start script
      run: "wget https://raw.githubusercontent.com/mambisi/ain-snapshotutil/master/start.sh"
    - run: chmod +x ./start.sh
    - run: cp /src/defid defid
    - run: cp /src/defi-cli defi-cli
#     - run: chmod +x ./defi-cli
#     - run: chmod ./defid
    - name: Run Node
      run: ./defid -daemon
    - name: Monitor running Node
      run: ./start.sh
  # Sync 550000 - 600000
#   sync-550000-600000:
#     runs-on: [self-hosted, linux, x64]
#     needs: build-binaries
#     container:
#       image : gcr.io/br-blockchains-dev/datadir-550000
#       volumes:
#         - datadir-550000
#       env:
#         STOP_BLOCK: 600000
#     timeout-minutes: 4320
#     steps:
#     - name: Download Defid
#       uses: actions/download-artifact@v3
#       with:
#         name: defid
#         path: defid
#     - name: Download Defi Cli
#       uses: actions/download-artifact@v3
#       with:
#         name: defi-cli
#         path: ./defi-cli
#     - name: download start script
#       run: "wget https://raw.githubusercontent.com/mambisi/ain-snapshotutil/master/start.sh"
#     - run: chmod +x ./start.sh
#     - run: chmod +x ./defi-cli
#     - run: chmod +x ./defid
#     - name: Run Node
#       run: ./defid -daemon
#     - name: Monitor running Node
#       run: ./start.sh
#   # Sync 600000 - 650000
#   sync-600000-650000:
#     runs-on: [self-hosted, linux, x64]
#     needs: build-binaries
#     container:
#       image : gcr.io/br-blockchains-dev/datadir-600000
#       volumes:
#         - datadir-600000
#       env:
#         STOP_BLOCK: 650000
#     timeout-minutes: 4320
#     steps:
#     - name: Download Defid
#       uses: actions/download-artifact@v3
#       with:
#         name: defid
#         path: defid
#     - name: Download Defi Cli
#       uses: actions/download-artifact@v3
#       with:
#         name: defi-cli
#         path: ./defi-cli
#     - name: download start script
#       run: "wget https://raw.githubusercontent.com/mambisi/ain-snapshotutil/master/start.sh"
#     - run: chmod +x ./start.sh
#     - run: chmod +x ./defi-cli
#     - run: chmod +x ./defid
#     - name: Run Node
#       run: ./defid -daemon
#     - name: Monitor running Node
#       run: ./start.sh
#   # Sync 650000 - 700000
#   sync-650000-700000:
#     runs-on: [self-hosted, linux, x64]
#     needs: build-binaries
#     container:
#       image : gcr.io/br-blockchains-dev/datadir-650000
#       volumes:
#         - datadir-650000
#       env:
#         STOP_BLOCK: 700000
#     timeout-minutes: 4320
#     steps:
#     - name: Download Defid
#       uses: actions/download-artifact@v3
#       with:
#         name: defid
#         path: defid
#     - name: Download Defi Cli
#       uses: actions/download-artifact@v3
#       with:
#         name: defi-cli
#         path: ./defi-cli
#     - name: download start script
#       run: "wget https://raw.githubusercontent.com/mambisi/ain-snapshotutil/master/start.sh"
#     - run: chmod +x ./start.sh
#     - run: chmod +x ./defi-cli
#     - run: chmod +x ./defid
#     - name: Run Node
#       run: ./defid -daemon
#     - name: Monitor running Node
#       run: ./start.sh
