name: ParallelTesting
on:
  push:
    branches:
      - parallel-test
  pull_request:
    branches:
      - parallel-test
jobs:
  build-binaries:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Node
      run: ./make.sh build
  sync-350000-400000:
    runs-on: [self-hosted, linux, x64]
    needs: build-binaries
    container:
      image : gcr.io/br-blockchains-dev/datadir-350000
      volumes:
        - ${{ github.workspace }}/src:/src
        - ${{ github.workspace }}/ci/parallel_sync:/parallel_sync
      options: --privileged
      env:
        STOP_BLOCK: 400000
        DEFID_BIN: /src/defid
        DEFI_CLI_BIN: /src/defi-cli
    timeout-minutes: 4320
    steps:
    - name: Start Node
      run: /parallel_sync/sync_then_diff.sh
  sync-400000-450000:
    runs-on: [self-hosted, linux, x64]
    needs: build-binaries
    container:
      image : gcr.io/br-blockchains-dev/datadir-400000
      volumes:
        - ${{ github.workspace }}/src:/src
        - ${{ github.workspace }}/ci/parallel_sync:/parallel_sync
      options: --privileged
      env:
        STOP_BLOCK: 450000
        DEFID_BIN: /src/defid
        DEFI_CLI_BIN: /src/defi-cli
    timeout-minutes: 4320
    steps:
    - name: Start Node
      run: /parallel_sync/sync_then_diff.sh
  sync-450000-500000:
    runs-on: [self-hosted, linux, x64]
    needs: build-binaries
    container:
      image : gcr.io/br-blockchains-dev/datadir-450000
      volumes:
        - ${{ github.workspace }}/src:/src
        - ${{ github.workspace }}/ci/parallel_sync:/parallel_sync
      options: --privileged
      env:
        STOP_BLOCK: 500000
        DEFID_BIN: /src/defid
        DEFI_CLI_BIN: /src/defi-cli
    timeout-minutes: 4320
    steps:
    - name: Start Node
      run: /parallel_sync/sync_then_diff.sh
  sync-500000-550000:
    runs-on: [self-hosted, linux, x64]
    needs: build-binaries
    container:
      image : gcr.io/br-blockchains-dev/datadir-500000
      volumes:
        - ${{ github.workspace }}/src:/src
        - ${{ github.workspace }}/ci/parallel_sync:/parallel_sync
      options: --privileged
      env:
        STOP_BLOCK: 550000
        DEFID_BIN: /src/defid
        DEFI_CLI_BIN: /src/defi-cli
    timeout-minutes: 4320
    steps:
    - name: Start Node
      run: /parallel_sync/sync_then_diff.sh
