name: Build - Dev

on:
  workflow_dispatch:
  push:
    tags:
      - "!v*"
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_VERSION: latest # Computed
  DOCKER_HUB_USER: defi

jobs:
  linux-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Populate environment
      run: GIT_VERSION=1 ./make.sh ci-export-vars

    - name: Build and package
      run: GIT_VERSION=1 TARGET="x86_64-pc-linux-gnu" ./make.sh docker-release

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: defichain-${{ env.BUILD_VERSION }}-x86_64-pc-linux-gnu
        path: ./build/defichain-${{ env.BUILD_VERSION }}-x86_64-pc-linux-gnu.tar.gz

  linux-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Populate environment
      run: GIT_VERSION=1 ./make.sh ci-export-vars
    
    - name: Build and package
      run: GIT_VERSION=1 TARGET="aarch64-linux-gnu" ./make.sh docker-release

    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: defichain-${{ env.BUILD_VERSION }}-aarch64-linux-gnu
        path: ./build/defichain-${{ env.BUILD_VERSION }}-aarch64-linux-gnu.tar.gz

  linux-armhf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Populate environment
      run: GIT_VERSION=1 ./make.sh ci-export-vars
    
    - name: Build and package
      run: GIT_VERSION=1 TARGET="arm-linux-gnueabihf" ./make.sh docker-release

    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: defichain-${{ env.BUILD_VERSION }}-arm-linux-gnueabihf
        path: ./build/defichain-${{ env.BUILD_VERSION }}-arm-linux-gnueabihf.tar.gz

  win-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Populate environment
      run: GIT_VERSION=1 ./make.sh ci-export-vars
    
    - name: Build and package
      run: GIT_VERSION=1 TARGET="x86_64-w64-mingw32" ./make.sh docker-release

    - name: Publish artifact - x86_64-w64-mingw32
      uses: actions/upload-artifact@v3
      with:
        name: defichain-${{ env.BUILD_VERSION }}-x86_64-w64-mingw32
        path: ./build/defichain-${{ env.BUILD_VERSION }}-x86_64-w64-mingw32.tar.gz

  osx-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Populate environment
      run: GIT_VERSION=1 ./make.sh ci-export-vars

    - name: Build and package
      run: GIT_VERSION=1 TARGET="x86_64-apple-darwin" ./make.sh docker-release

    - name: Publish artifact - x86_64-apple-darwin
      uses: actions/upload-artifact@v3
      with:
        name: defichain-${{ env.BUILD_VERSION }}-x86_64-apple-darwin
        path: ./build/defichain-${{ env.BUILD_VERSION }}-x86_64-apple-darwin.tar.gz

  osx-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Populate environment
      run: GIT_VERSION=1 ./make.sh ci-export-vars

    - name: Build and package
      run: GIT_VERSION=1 TARGET="aarch64-apple-darwin" ./make.sh docker-release

    - name: Publish artifact - aarch64-apple-darwin
      uses: actions/upload-artifact@v3
      with:
        name: defichain-${{ env.BUILD_VERSION }}-aarch64-apple-darwin
        path: ./build/defichain-${{ env.BUILD_VERSION }}-aarch64-apple-darwin.tar.gz

  multi-arch-docker-build:
    needs: [linux-x64, linux-aarch64, linux-armhf]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3

    - name: Populate environment
      run: GIT_VERSION=1 ./make.sh ci-export-vars

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build defi image (linux-x64)
      run: GIT_VERSION=1 TARGET="x86_64-pc-linux-gnu" ./make.sh docker-buildx

    - name: Build defi image (linux-aarch64)
      run: GIT_VERSION=1 TARGET="aarch64-linux-gnu" ./make.sh docker-buildx

    - name: Build defi image (linux-armhf)
      run: GIT_VERSION=1 TARGET="arm-linux-gnueabihf" ./make.sh docker-buildx

    # Create manifest list and publish multi-arch images
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push multi-arch images to Docker Hub
      run: |
        set -e; ver=${{ env.BUILD_VERSION }}
        docker tag defichain-defi-x86_64-pc-linux-gnu:${ver} defi/defichain:${ver}-x64
        docker tag defichain-defi-aarch64-linux-gnu:${ver} defi/defichain:${ver}-arm64
        docker tag defichain-defi-arm-linux-gnueabihf:${ver} defi/defichain:${ver}-arm
        docker push defi/defichain:${ver}-x64
        docker push defi/defichain:${ver}-arm64
        docker push defi/defichain:${ver}-arm

    - name: Create and push manifest list to Docker Hub
      run:
        docker manifest create defi/defichain:${ver} defi/defichain:${ver}-x64 defi/defichain:${ver}-arm64 defi/defichain:${ver}-arm
        docker manifest annotate --arch amd64 defi/defichain:${ver} defi/defichain:${ver}-x64
        docker manifest annotate --arch arm64 defi/defichain:${ver} defi/defichain:${ver}-arm64
        docker manifest annotate --arch arm defi/defichain:${ver} defi/defichain:${ver}-arm
        docker manifest inspect defi/defichain:${ver}
        docker manifest push defi/defichain:${ver}
